import Head from "next/head";
import Navbar from "../../Components/Home/Navbar.js"
import Hero from "../../Components/Home/Hero.js"
import Story from "../../Components/Home/Story.js";
import Paintings from "../../Components/Home/Paintings.js";
import Sculpture from "../../Components/Home/Sculpture.js";
import Events from "../../Components/Home/Events.js";
import Footer from "../../Components/Home/Footer.js";

export default function Home() {
  return (
    <>
      <Head>
        <title>Seema Jain</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Hero />
        <Story />
        <Paintings />
        <Sculpture />
        {/* <Events /> */}
        <Footer/>
      </main>
    </>
  );
}
