const data = [
  { id:'1',
  name: 'Amity Peace Poems',
  url:'/virtualgallery/amity peace poems.jpeg',
},
{ id:'2',
  name: 'Agst',
  url:'/virtualgallery/angst.jpeg',
},
{ id:'3',
  name: 'Celebrating time travel',
  url:'/virtualgallery/celebrating time travel.jpeg',
},
{ id:'4',
  name: 'Cityscapes',
  url:'/virtualgallery/cityscapes.jpeg',
},
{ id:'5',
  name: 'An anthology of contemporary south asian women poetry',
  url:'/virtualgallery/an anthology of contemporary south asian women poetry.jpeg',
},
{ id:'6',
  name: 'Antargata',
  url:'/virtualgallery/antargata.jpeg',
},
{ id:'7',
  name: 'Auburn ambrosia',
  url:'/virtualgallery/auburn ambrosia.jpeg',
},
{ id:'8',
  name: 'Cosmic poetry',
  url:'/virtualgallery/cosmic poetry.jpeg',
},
{ id:'9',
  name: 'Cuckoo in crisis',
  url:'/virtualgallery/cuckoo in crisis.jpeg',
},
{ id:'10',
  name: 'Effloroscence 2021',
  url:'/virtualgallery/effloroscence 2021.jpeg',
},
{ id:'11',
  name: 'Effloroscence 2023',
  url:'/virtualgallery/effloroscence 2023.jpeg',
},
{ id:'12',
  name: 'Flame of a distant mountain',
  url:'/virtualgallery/flame of a distant mountain.jpeg',
},
{ id:'13',
  name: 'Global contemporary fiction',
  url:'/virtualgallery/global contemporary fiction.jpeg',
},
{ id:'14',
  name: "I won't find another you",
  url:"/virtualgallery/i won't find another you.jpeg",
},
{ id:'15',
  name: 'IPA 2020',
  url:'/virtualgallery/ipa 2020.jpeg',
},
{ id:'16',
  name: 'Kavya kaumudi',
  url:'/virtualgallery/kavya kaumudi.jpeg',
},
{ id:'17',
  name: 'Muse of now paradigm',
  url:'/virtualgallery/muse of now paradigm.jpeg',
},
{ id:'18',
  name: 'Pixie dust and all things magical',
  url:'/virtualgallery/pixie dust and all things magical.jpeg',
},
{ id:'19',
  name: 'Poetry on a plate with spicy mango pickle',
  url:'/virtualgallery/poetry on a plate with spicy mango pickle.jpeg',
},
{ id:'20',
  name: 'Poets and poetry',
  url:'/virtualgallery/poets and poetry.jpeg',
},
{ id:'21',
  name: 'Redolent rush',
  url:'/virtualgallery/redolent rush.jpeg',
},
{ id:'22',
  name: 'Songs of perigrinators',
  url:'/virtualgallery/songs of perigrinators.jpeg',
},
{ id:'23',
  name: 'Soul spaces',
  url:'/virtualgallery/soul spaces.jpeg',
},
{ id:'24',
  name: 'Tapestry of women in indian mythology',
  url:'/virtualgallery/tapestry of women in indian mythology.jpeg',
},
{ id:'25',
  name: 'The well earned poems',
  url:'/virtualgallery/the well earned poems.jpeg',
},
{ id:'26',
  name: 'Shajar ki chanv tal',
  url:'/virtualgallery/Shajar ki chanv tal.jpeg',
},
{ id:'27',
  name: 'Goonj',
  url:'/virtualgallery/Goonj.jpeg',
},
]

export default data;